# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1de0af6369e07e47125e3877fabcee3fbf17412f5856d109280f71432e7f18f5bd9bbb0346a3bbfd93bc53fc798429d742bca8824020817a07750c238608a56

test:
  secret_key_base: 1672d9cc0c8c479be7a64d3e73f0843e8e47542a15354f48c60b257e3c0fbab2846cb6634a84b92537fcf680c22e54bfa22089b791faee40dca0e5039cf9e4e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
